version: '3.8'

# 定义统一的网络
networks:
  elastic:
    driver: bridge  
    name: elastic

services:
  # --- Logstash 服务 ---
  logstash:
    image: elastdocker/logstash:${ELK_VERSION}
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./secrets/certs/ca/ca.crt:/certs/ca.crt:ro

    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      LS_JAVA_OPTS: "-Xmx${LOGSTASH_HEAP} -Xms${LOGSTASH_HEAP} -Dlog4j2.formatMsgNoLookups=true"
      CUSTOMER_NAMESPACE: ${CUSTOMER_NAMESPACE}
    ports:
      - "514:514/udp"
      - "514:514/tcp"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-s", "-XGET", "http://127.0.0.1:9600"]
    logging:
      options:
        max-size: 100m
    networks:
      - elastic

  # --- Portainer Agent ---
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - elastic

  # --- Portainer CE ---
  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - elastic
    depends_on:
      - agent

  # --- Nginx 服务 ---
  nginx:
    image: nginx:stable
    hostname: "nginx"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /elastdocker/package:/elastdocker/package 
      - ./nginx/certs:/etc/ssl/certs
    ports:
      - "9200:9200"   # Elasticsearch HTTPS
      - "8220:8220"   # Fleet server
    logging:
      options:
        max-size: 100m
    networks:
      - elastic


