user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  8192;
}

stream {

    log_format tcp_log '$remote_addr:$remote_port -> $upstream_addr [$time_local] $bytes_sent $bytes_received $session_time';
    access_log /var/log/nginx/stream_access.log tcp_log;
    server {
        listen 9200;
        proxy_pass 172.18.6.110:9200;
        proxy_connect_timeout 5s;   # 连接建立超时
        proxy_timeout 10s;
    }    

    server {
        listen 8220;
        proxy_pass 172.18.6.110:8220;
        proxy_connect_timeout 5s;
        proxy_timeout 30s;   
    }

}
