input {
    kafka {
        bootstrap_servers => "kafka1:9092"
        consumer_threads => 12
        topics => ["otherlog"]
        group_id => "drs"
        decorate_events => true
    }
}

filter {

  mutate {
      remove_field => ["_temp_","[event][original]"]
  }

}

output {

if [@metadata][kafka][topic] == "otherlog" {
    elasticsearch {
        hosts => "${ELASTICSEARCH_HOST_PORT}"
        user=> "${ELASTIC_USERNAME}"
        password => "${ELASTIC_PASSWORD}"
        data_stream => "true"
        data_stream_dataset => "kafka_log.otherlog"
        data_stream_namespace => "${CUSTOMER_NAMESPACE}"
        #pipeline => "logs-panw.panos-3.15.0-copy"
        ssl => true
        ssl_certificate_verification => false
        cacert => "/certs/ca.crt"
    }
}

}